Wardship/Models/QuickSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using PagedList;
using System.Security;


namespace Wardship.Models
{
    public class QuickSearch : ListViewModel
    {

        // applicant address details 
        #region Applicant Search Details

        [Display(Name = "Applicant Name")]
        [MaxLength(8), DataType(DataType.Text)]
        public string ApplicantName { get; set; }

        [Display(Name = "Address Line 1")]
        [MaxLength(100), DataType(DataType.Text)]
        public string ApplicantAddr1 { get; set; }

        [Display(Name = "Address Line 2")]
        [MaxLength(100), DataType(DataType.Text)]
        public string ApplicantAddr2 { get; set; }

        [Display(Name = "Address Line 3")]
        [MaxLength(100), DataType(DataType.Text)]
        public string ApplicantAddr3 { get; set; }

        [Display(Name = "Address Line 4")]
        [MaxLength(100), DataType(DataType.Text)]
        public string ApplicantAddr4 { get; set; }

        [Display(Name = "Postcode")]
        [MaxLength(8), DataType(DataType.Text)]
        public string ApplicantPostcode { get; set; }

        #endregion

        //builds the address with out spaces
        public virtual List<string> populatedLines
        {
            get
            {
                List<string> outputAddress = new List<string>();
                outputAddress.Add(ApplicantName);
                outputAddress.Add(ApplicantAddr1);
                if (ApplicantAddr2 != null) outputAddress.Add(ApplicantAddr2);
                if (ApplicantAddr3 != null) outputAddress.Add(ApplicantAddr3);
                if (ApplicantAddr4 != null) outputAddress.Add(ApplicantAddr4);
                if (ApplicantPostcode != null) outputAddress.Add(ApplicantPostcode);

                return outputAddress;
            }
        }

        //Security element replaces invalid xml with equivilant when using the address block above
        public virtual string printAddressMultiLine
        {
            get
            {
                List<string> PopulateLines = new List<string>();
                foreach (var line in populatedLines)
                {
                    PopulateLines.Add(SecurityElement.Escape(line));
                }
                return string.Join("<w:br/>", PopulateLines.ToArray());
            }
        }





//search details 



        //Key](NONE)
        public int WardshipCaseID { get; set; }

        [Display(Name = "File Number")]
        [DataType(DataType.Text)]
        public string FileNumber { get; set; }

        [Display(Name = "Child Surname")]
        [DataType(DataType.Text)]
        [MaxLength(100)]
        public string ChildSurname { get; set; }

        [Display(Name = "Child Forename")]
        [MaxLength(100)]
        [DataType(DataType.Text)]
        public string ChildForenames { get; set; }


        public virtual string ChildOutputName // Full Name 
        {
            get { return string.Format("{0} {1}", ChildForenames, ChildSurname); }
        }


        [Display(Name = "Child Date Of Birth")]
        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "0:d", ApplyFormatInEditMode = true), UIHint("DatePicker")]
        public DateTime? ChildDateofBirth { get; set; }

  

        public Boolean isValid()
        {
            //check each variable for validity, if not valid - set result to true
            if (FileNumber != null) { return true; }
            if (ChildSurname != null) { return true; }
            if (ChildForenames != null) { return true; }
            if (ChildDateofBirth != null) { return true; }
          

            //if no criteria is valid, return false as default
            return false;
        }

         public IPagedList<Wardship.Models.WardshipRecord> results { get; set; }
        // results object for a list of data which we will send to my controllor and view






    }







}

Wardship/Controllers/QuickSearchController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Wardship.Models;
using PagedList;
using System.Xml;
using System.Text;
using TPLibrary.Logger;

namespace Wardship.Controllers
{
    [Authorize]
    [ValidateAntiForgeryTokenOnAllPosts]
    public class QuickSearchController : Controller
    {
        private readonly ISQLRepository db;
        private readonly ICloudWatchLogger _logger;

        public QuickSearchController(ISQLRepository repository, ICloudWatchLogger logger)
        {
            db = repository;
            _logger = logger;
        }


        // GET: /QuickSearch/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PoPupDetails(int id)
        {
            WardshipRecord model = db.GetWardshipRecordByID(id);
            return PartialView("_PopupDetails", model);

        }

        //go to Wardship index
        public ActionResult Homeindex()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Index(QuickSearch model)
        {
            try
            {
                if (model != null && model.isValid())//if not equal to null build list of results 
                {
                    #region New search type

                    model.page = model.page ?? 1;

                    if (model.FileNumber != null)// search criteria 
                    {
                        model.results = db.QuickSearchByNumber(model.FileNumber).ToPagedList(model.page ?? 1, 15);
                    }
                    if (model.ChildSurname != null)
                    {
                        model.results = db.QuickSearchSurname(model.ChildSurname).ToPagedList(model.page ?? 1, 15);
                    }
                    if (model.ChildForenames != null)
                    {
                        model.results = db.QuickSearchByForename(model.ChildForenames).ToPagedList(model.page ?? 1, 15);
                    }
                    if (model.ChildDateofBirth != null)
                    {
                        model.results = db.QuickSearchByDOB(model.ChildDateofBirth).ToPagedList(model.page ?? 1, 15);
                    }


                    //////Adding Audit for new record - Commented as it fails and I have checked the database and it's not really used
                    ////var Audit = new AuditEvent();

                    ////Audit.EventDate = DateTime.Now;
                    ////Audit.UserID = (User as Wardship.ICurrentUser).DisplayName;
                    ////Audit.idAuditEventDescription = "New Search Made";
                    ////Audit.ChildForenames = model.ChildForenames;
                    ////Audit.ChildSurname = model.ChildSurname;
                    ////Audit.ChildDateofBirth = model.ChildDateofBirth;

                    //////Audit.RecordChanged = model.WardshipCaseID.ToString();

                    ////db.AddAuditEvent(Audit);
                    //////


                    return View("Results", model);
                    //return View(model);


                    #endregion

                }
                //return View(model);
                return View("Results", model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Exception in QuickSearchController in Index method, for user {User.Identity.Name}");
                return View("Error");
            }
         }




        public ActionResult CompleteForPrinting(int id, QuickSearch model)
        {   
            int WardshipCaseID;
            //1st Pass still using temp data to pass through "WardshipCaseID" 
            WardshipCaseID = id; //so creating a new instance of the ID if it exists

            TempData["WardshipCaseID"] = WardshipCaseID;    //putting all field values into Tempdata
                                                            //Then sending the data to my Print action
    
            return View();
        }



        [HttpPost]
        public ActionResult Print(QuickSearch model) ///int WardshipCaseID
        {
            int RefNum = 0;
            try
            {
                int WardshipCaseID = (int)TempData["WardshipCaseID"]; // setting the ID fron 0 = no ID  0< = found ID 

                TemplateListVM Amodel = new TemplateListVM();
                
                if (WardshipCaseID == 0) //Print Not found letter
                {
                    Amodel.templateID = 1;//template id
                }
                else if (WardshipCaseID > 0) // Print Search found letter
                {
                    Amodel.templateID = 2;//template id
                }
                RefNum = Amodel.templateID;
                //Load The WardshipCase object's 
                WardshipRecord WardshipRecord = db.GetWardshipRecordByID(WardshipCaseID);

                //Load The Template object
                WordTemplate template = db.GetTemplateByID(RefNum);

                //Create XML object for Template & put data in
                XmlDocument xDoc = new XmlDocument();

                //Set XML data of doument from template object
                xDoc.InnerXml = template.templateXML;

                //Applicant address
                xDoc.InnerXml = xDoc.InnerXml.Replace("||ADDRESS||", model.printAddressMultiLine);
                //References
                xDoc.InnerXml = xDoc.InnerXml.Replace("||DATE||", DateTime.Today.ToShortDateString());

                if (WardshipCaseID != 0)
                {
                  
               
                    //some child names can be blank
                    if (WardshipRecord.ChildForenames != null && WardshipRecord.ChildSurname != null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", WardshipRecord.ChildOutputName.ToString());
                    }
                    if (WardshipRecord.ChildForenames == null && WardshipRecord.ChildSurname != null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", WardshipRecord.ChildSurname.ToString());
                    }
                    if (WardshipRecord.ChildForenames != null && WardshipRecord.ChildSurname == null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", WardshipRecord.ChildForenames.ToString());
                    }

                }

                else
                {
                    AuditEvent Auditmodel = new AuditEvent();
                    Auditmodel = db.AuditEventsGetAll().LastOrDefault();

                    if (Auditmodel.ChildForenames != null && Auditmodel.ChildSurname != null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", Auditmodel.ChildOutputName.ToString());
                    }
                    if (Auditmodel.ChildForenames == null && Auditmodel.ChildSurname != null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", Auditmodel.ChildSurname.ToString());
                    }
                    if (Auditmodel.ChildForenames != null && Auditmodel.ChildSurname == null)
                    {
                        xDoc.InnerXml = xDoc.InnerXml.Replace("||CHILDFULLNAME||", Auditmodel.ChildForenames.ToString());
                    }

                }
               

                //USERNAME
                xDoc.InnerXml = xDoc.InnerXml.Replace("||USERNAME||", (User as Wardship.ICurrentUser).DisplayName);

                //Return saved document (to the screen with the data embedded....)
                return File(ConvertToBytes(xDoc), "application/msword", template.templateName + ".doc"); //return byte version

            }
            catch (Exception ex)
            {
                // redirect to error page
                ErrorModel errModel = new ErrorModel(2);
                errModel.ErrorMessage = string.Format("Could not load SearchTemplate {0}", RefNum);
                TempData["ErrorModel"] = errModel;
                _logger.LogError(ex, $"Exception in QuickSearchController in Print method, for user {User.Identity.Name}");
                return RedirectToAction("IndexByModel", "Error", new { area = "", model = errModel ?? null });
            }


        }



        public static byte[] ConvertToBytes(XmlDocument doc)
        {
            Encoding encoding = Encoding.UTF8;
            byte[] docAsBytes = encoding.GetBytes(doc.OuterXml);
            return docAsBytes;
        }

  
    }
}

Wardship/Views/QuickSearch/CompleteForPrinting.cshtml
@model Wardship.Models.QuickSearch

@{
    ViewBag.Title = "PrintLetter";
}

<h1>Quick search result - Complete for printing</h1>
<h6>@Html.ActionLink("Reset Form", "Index") > Search</h6>

@using (Html.BeginForm("print", "QuickSearch", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <fieldset>

    <legend>Enter applicant address details</legend>
  
  <br /> 
        <div class="display-label">Name</div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantName)
            @Html.ValidationMessageFor(model => model.ApplicantName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApplicantAddr1, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantAddr1)
            @Html.ValidationMessageFor(model => model.ApplicantAddr1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApplicantAddr2, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantAddr2)
            @Html.ValidationMessageFor(model => model.ApplicantAddr2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApplicantAddr3, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantAddr3)
            @Html.ValidationMessageFor(model => model.ApplicantAddr3)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApplicantAddr4, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantAddr4)
            @Html.ValidationMessageFor(model => model.ApplicantAddr4)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApplicantPostcode, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApplicantPostcode)
            @Html.ValidationMessageFor(model => model.ApplicantPostcode)
        </div>


    </fieldset>

    
    <fieldset>

    <legend>Print letter</legend>
     <br />
    <p>Click the button to print the letter</p> 
    <input type="submit" value=" Print Letter " style="border-size: 0px;border-style: none; background: inherit;font: inherit; color: blue;cursor: hand;cursor: pointer; padding: 0px;" />

    </fieldset>
    
    
    
} 

Wardship/Views/QuickSearch/Index.cshtml
@model Wardship.Models.QuickSearch

@{
    ViewBag.Title = "Index";
}

<h1>Quick search</h1>
<h6>@Html.ActionLink("Reset Form", "Index") > Search</h6>


@using (Html.BeginForm("Index", "QuickSearch", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <fieldset>

    <legend>Enter Search Criteria</legend> 
  
  <br /> 
        <div class="editor-label">
            @Html.LabelFor(model => model.FileNumber, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FileNumber)
            @Html.ValidationMessageFor(model => model.FileNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChildSurname, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ChildSurname)
            @Html.ValidationMessageFor(model => model.ChildSurname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChildForenames, true)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ChildForenames)
            @Html.ValidationMessageFor(model => model.ChildForenames)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChildDateofBirth, true)
        </div>
        <div class="editor-field">
           @Html.EditorFor(model => model.ChildDateofBirth)
           @Html.ValidationMessageFor(model => model.ChildDateofBirth)
        </div>

       <p>
            <input type="submit" value="Search" />
            
        </p>
    </fieldset>
}

   
 

Wardship/Views/QuickSearch/Results.cshtml
@model Wardship.Models.QuickSearch


@{
    ViewBag.Title = "Results";
}

<link href="@Url.Content("~/Content/newPagedListButtons.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" type="text/css" />
   
  <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
  <script src="../../Scripts/jquery-ui-1.8.11.min.js" type="text/javascript"></script>
  
    
<script type="text/javascript">            // Remark: all this javascript could be placed in a separate js file
    // to avoid cluttering the views. The first three lines fires up any action link set to the "openDialog"
    $(document).ready(function () {
        $(".openDialog").live("click", function (e, p) {
            e.preventDefault();
            var title = 'Wardship Details For: ' + this.getAttribute("data_title");
            
            $('#dialog').load(this.href, function () {
                $(this).dialog({
                    open: function (event, ui) { $('#Details').focus(); },
                    title: title,
                    modal: true,
                    width: 600,

                    resizable: false,

                    //  $( "#dialog-message" ).dialog    ( Close: function was Ok:function )
                    buttons: { Close: function () { $(this).dialog("close"); }  }
                });
            });
            return false;
        });
    });

</script>



@*Empty div so that the java sctipts will place the action link in hear as a popup with my partial view .*@


<h1>Quick search results</h1>

<h6>@Html.ActionLink("Reset Form", "Index") > Results</h6>
 
<div id="dialog"></div>           


 @if (Model != null && Model.results != null && Model.results.Count() == 0)
    {   
     <div class="message error" style="padding:10px;">
				<span></span>
				<h6>Attention</h6>
				<p>No records match the criteria, please search again</p>
	</div>
    


<br />    
     
   <fieldset>
                 
  <legend>No Matches Found</legend>

        <p>Click the link below to add Applicant details and print the "no trace" letter</p>

      @using (Html.BeginForm("Print", "QuickSearch"))
      {
        @Html.AntiForgeryToken()
          <div>
                  
                    @Html.HiddenFor(model => model.FileNumber)
                    @Html.HiddenFor(model => model.ChildSurname)
                    @Html.HiddenFor(model => model.ChildForenames)
                    @Html.HiddenFor(model => model.ChildDateofBirth)
                    @Html.HiddenFor(model => model.WardshipCaseID)
                   
                    @Html.ImageAndTextLink(Url.Content("~/Content/Images/tick.png"), "Click here", "Add applicant details", "CompleteForPrinting", "QuickSearch", new { id = 0 }, null, null, "createButton")
 
                    </div> 

      }
    </fieldset>


    }

// model is created and the results are empty (stopping searches without critera ) !!!!
    else if (Model != null && Model.results == null)
    {
    
     <div class="message error" style="padding:10px;">
				<span></span>
				<h6>Attention</h6>
				<p>Please enter a search criteria</p>
	</div>
     
    }


//model is created and there is matching data in one of the fields!!!!!!
    else if (Model != null && Model.results != null && Model.results.Count() > 0)
    {
    <div class="message ok" style="padding:10px;">
				<span></span>
				<h6>Success</h6>
				<p>Wardships found for matching criteria</p>
    @*            <p>@Model.message</p>*@

	</div>
    

       
<p>Total number of records found equals: @Model.results.Count()</p>
<table>
    <tr>
        <th>Details</th>
        <th>File Number</th>
        <th>Child Forename</th>
        <th>Child Surname</th>
        <th>Child Date of Birth</th>
        <th>Gender</th>
        <th>Date Issue</th>
@*        <th>Lapse Letter Sent</th>
        <th>First Appointment Date</th>*@
        <th>Hearing Date</th>

        <th>Select and add applicant address</th>

    </tr>
      
    @* must use the model. as we declared our QuickSearch above to show results from the model we created.*@

    @foreach (var item in Model.results)
    {
        <tr>
  
           <td>@Html.ImageLink(Url.Content("~/Content/Images/view.png"), "Details", "PoPupDetails", "QuickSearch", new { id = item.WardshipCaseID }, new { @class = "openDialog", data_title = item.FileNumber }, null)</td>

           <td>@Html.DisplayFor(modelItem => item.FileNumber)</td>
           <td>@Html.DisplayFor(modelItem => item.ChildForenames)</td>
           <td>@Html.DisplayFor(modelItem => item.ChildSurname)</td>
           <td>@Html.DisplayFor(modelItem => item.ChildDateofBirth)</td>
           <td>@Html.DisplayFor(modelitem => item.Gender.Detail)</td>
           <td>@Html.DisplayFor(modelitem => item.DateOfOS)</td>
@*           <td>@Html.DisplayFor(modelitem => item.LapseLetterSent)</td>
           <td>@Html.DisplayFor(modelitem => item.FirstAppointmentDate)</td>*@
           <td>@Html.DisplayFor(modelitem => item.HearingDate)</td>

          
           <td>

            @using (Html.BeginForm("Print", "QuickSearch"))
            {
             @Html.AntiForgeryToken()
             @Html.HiddenFor(model => model.ApplicantName)
             @Html.HiddenFor(model => model.ApplicantAddr1)
             @Html.HiddenFor(model => model.ApplicantAddr2)
             @Html.HiddenFor(model => model.ApplicantAddr3)
             @Html.HiddenFor(model => model.ApplicantAddr4)
             @Html.HiddenFor(model => model.ApplicantPostcode)
             @Html.HiddenFor(model => model.WardshipCaseID, item.WardshipCaseID, null) 
             @Html.ImageAndTextLink(Url.Content("~/Content/Images/tick.png"), "Click here", "Add applicant details", "CompleteForPrinting", "QuickSearch", new { id = item.WardshipCaseID }, null, null, "createButton")
            }
           
           </td>
        </tr>
    }
    <tr>
        <td colspan="8">
            @{
                var token2 = @Html.AntiForgeryToken().ToHtmlString();

                var beginIndex2 = token2.IndexOf("value=\"") + 7;
                var endIndex2 = token2.IndexOf("\"", beginIndex2);
                token2 = token2.Substring(beginIndex2, endIndex2 - beginIndex2);

            }

            @Html.SSGPaging("Results", "QuickSearch", Model, Model.results, token2)
        </td>
    </tr>

</table>
    
    <br />   
    <br />
    <br />   
        
        
     <fieldset>
     <legend>No Matches Found</legend>

        <p>Click the link below to add Applicant details and print the "no trace" letter</p>

       @using (Html.BeginForm("Print", "QuickSearch"))
       { 
            <div>
                @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.FileNumber)
            @Html.HiddenFor(model => model.ChildSurname)
            @Html.HiddenFor(model => model.ChildForenames)
            @Html.HiddenFor(model => model.ChildDateofBirth)
            @Html.HiddenFor(model => model.WardshipCaseID)
            @Html.ImageAndTextLink(Url.Content("~/Content/Images/tick.png"), "Click here", "Add applicant details", "CompleteForPrinting", "QuickSearch", new { id = 0 }, null, null, "createButton")
           
            </div> 
       }

    </fieldset> 
     
    
    }

Wardship/Views/QuickSearch/_PopupDetails.cshtml
@model Wardship.Models.WardshipRecord



<fieldset>

    <legend>Child's Details</legend>

    <div class="display-label">Wardship Number</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FileNumber)
    </div>

    <div class="display-label">Child Surname</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChildSurname)
    </div>
    <div class="display-label">Child Forenames</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChildForenames)
    </div>

    <div class="display-label">Case Type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CaseType.Detail)
    </div>
    <div class="display-label">Type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type.Detail)
    </div>

    <div class="display-label">Court</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Court.CourtName)
    </div>

    <div class="display-label">Child Date of Birth</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChildDateofBirth)
    </div>
    
    <div class="display-label">Gender</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gender.Detail)
    </div>


    <div class="display-label">Date Issued</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateOfOS)
    </div>

    <div class="display-label">Record</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Record.Detail)
    </div>

    <div class="display-label">Judge</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DistrictJudge.Name)
    </div>

   
  
    
</fieldset>

<fieldset>
    
     <legend>Case Status</legend>
   

    <div class="display-label">Lapse letter sent</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LapseLetterSent)
    </div>

    <div class="display-label">Lapsed</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Lapsed.Detail)
    </div>

    <div class="display-label">Status</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status.Detail)
    </div>

    <div class="display-label">C.W.O. Involved</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CWO.Detail)
    </div>
    
    <div class="display-label">First appointment Taken</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstAppointmentDate)
    </div>

        <div class="display-label">Hearing Date</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HearingDate)
    </div>

    <div class="display-label">CAFCASS Involved</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CAFCASSInvolved.Detail)
    </div>
    
</fieldset>